#!/usr/bin/env python
"""Reassign a bug to a different person

"""

import fattybugs
import os
import sys
import getopt
import re

def usage():
    usage_str="""
USAGE:
Reassign a bug in the default database, as specified in the configuration file:
    fbdb_reassign_bug [-c CONFIGFILE] [ -a NEW_ASSIGNEE ] [ BUG_NAME ] 
        Default CONFIGFILE is either $HOME/.fattybugs or $USERPROFILE/.fattybugs

Reassign a bug in an alternate database file:
    fbdb_reassign_bug [ -d DATABASE ] [ -a NEW_ASSIGNEE ] [ BUG_NAME ] 

"""
    print(usage_str)

def main(argv):
    """Parse the arguments, then build the database"""
    configfile=None
    db_file=None
    bug_name=None
    assigned_to=None

    try:
        opts,args=getopt.getopt(argv,"hc:d:a:")
    except getopt.GetoptError():
        usage()
        sys.exit(2)

    for opt,arg in opts:
        if opt=="-h":
            usage()
            sys.exit()
        elif opt in ("-c"):
            configfile=arg
        elif opt in ("-d"):
            db_file=arg
        elif opt in ("-a"):
            assigned_to=arg

    if len(args) > 0:
        bug_name=args[0]
    if not db_file:
        if not configfile:
            configfile=fattybugs.default_configfile()
        db_file=fattybugs.default_bug_db(configfile)
        
    bdb=fattybugs.BugDB(db_file)
    existing_bugs=list(bdb.bugs(name_only=True))
    if bug_name and (bug_name not in existing_bugs):
        print("ERROR: The specified bug {} is not an active bug".format(bug_name),file=sys.stderr)
        sys.exit(2)
        
    if not bug_name:
        while bug_name not in existing_bugs:            
            print("*************")
            print("Active bugs:")
            for i,b in enumerate(existing_bugs):
                print(i+1,") ",b)
            print("*************")
            print("Selection options:")
            print("   # : Select the bug number #")
            print("   #h : More details about bug number #")
            print("   a : List details of all bugs")
            print("   q : Quit ")
            resp=input("Please enter your selection (#,#h,a)> ")
            try:
                bug_name=existing_bugs[int(resp)-1]
            except IndexError:
                print("ERROR: Invalid selection",file=sys.stderr)
            except (ValueError,TypeError):
                m=re.match(r"(\d+)+h$",resp)
                if m:                    
                    num=int(m.groups(1)[0])
                    bdb.bug_details_display(bug_name=existing_bugs[int(num)-1])
                elif resp.lower()=="a":
                    bdb.list_bugs()
                elif resp.lower()=="q":
                    sys.exit()
                
                else:
                    print("ERROR: Invalid selection",file=sys.stderr)

    if not assigned_to:
        assigned_to=input("Enter the value of the new assignee > ")
    bdb.reassign(assigned_to,bug_name=bug_name)

if __name__=="__main__":
    main(sys.argv[1:])



